spring:
  application:
    name: todo-backend
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  sql:
    init:
      platform: postgresql
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
gg:
  jte:
    usePrecompiledTemplates: true

server:
  port: ${PORT:8080}
